runtime: nodejs20
service: default
entrypoint: npm start
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 3
env_variables:
  AWS_S3_BUCKET: 's3-storage-react-app'
  AWS_REGION: 'eu-north-1'
  # Provide AWS credentials at deploy time; do not commit secret values.
secret_env_variables:
  - key: AWS_ACCESS_KEY_ID
    secret: aws-access-key-id
    version: latest
  - key: AWS_SECRET_ACCESS_KEY
    secret: aws-secret-access-key
    version: latest
