runtime: nodejs20
service: default
entrypoint: /bin/sh -c "if [ -f ./.env ]; then set -a; . ./.env; set +a; fi; exec npm start"
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 3
